const LandObj = {
  en_US: {
    please_enter_account: "Please enter a username. ",
    please_enter_pwd: "Please enter a password.",
    please_enter_access_code: "Please enter an access code.",
    login: "Login",
    accesscode: "Access Code",
    password: "Password",
    account: "Account",
    or: "or",
    one_click_login: "One-click Login",
    account_login: "Account Login",
    voucher_login: "Voucher Login",
  },
  es_ES: {
    please_enter_account: "Introduzca el nombre de usuario.",
    please_enter_pwd: "Introduzca la contraseña.",
    please_enter_access_code: "por favor ingrese el código de verificación.",
    login: "Iniciar sesión",
    accesscode: "Código de acceso",
    password: "Contraseña",
    account: "Cuenta",
    or: "o",
    one_click_login: "Un solo clic",
    account_login: "Cuenta",
    voucher_login: "Gutschein-Anmeldung",
  },
  ne_NP: {
    please_enter_account: "कृपया प्रयोगकर्ता नाम प्रविष्ट गर्नुहोस्।",
    please_enter_pwd: "कृपया पासवर्ड प्रविष्ट गर्नुहोस्।",
    please_enter_access_code: "कृपया पहुँच कोड प्रविष्ट गर्नुहोस्।",
    login: "लगइन",
    accesscode: "पहुँच कोड",
    password: "पासवर्ड",
    account: "खाता",
    or: "वा",
    one_click_login: "एक-क्लिक लगइन",
    account_login: "खाता लगइन",
    voucher_login: "भौचर लगइन",
  },
  dz_BT: {
    please_enter_account: "ཁྱོད་ཀྱི་སྤྱོད་མིང་བཙུགས་གནང་།",
    please_enter_pwd: "ཁྱོད་ཀྱི་ཨང་རྟགས་བཙུགས་གནང་།",
    please_enter_access_code: "འཛུལ་སྤྱོད་ཨང་བཙུགས་གནང་།",
    login: "ནང་འཛུལ",
    accesscode: "འཛུལ་སྤྱོད་ཨང་།",
    password: "ཨང་རྟགས",
    account: "རྩིས་ཁྲ",
    or: "ཡང་ན",
    one_click_login: "གཅིག་རྡེབ་ནང་འཛུལ",
    account_login: "རྩིས་ཁྲ་ནང་འཛུལ",
    voucher_login: "བོ་ཆར་ནང་འཛུལ",
  },
  hi_IN: {
    please_enter_account: "कृपया उपयोगकर्ता नाम दर्ज करें।",
    please_enter_pwd: "कृपया पासवर्ड दर्ज करें।",
    please_enter_access_code: "कृपया एक्सेस कोड दर्ज करें।",
    login: "लॉगिन",
    accesscode: "एक्सेस कोड",
    password: "पासवर्ड",
    account: "खाता",
    or: "या",
    one_click_login: "एक-क्लिक लॉगिन",
    account_login: "खाता लॉगिन",
    voucher_login: "वाउचर लॉगिन",
  },
  ko_KR: {
    please_enter_account: "사용자 이름을 입력하세요.",
    please_enter_pwd: "비밀번호를 입력하세요.",
    please_enter_access_code: "액세스 코드를 입력하세요.",
    login: "로그인",
    accesscode: "액세스 코드",
    password: "비밀번호",
    account: "계정",
    or: "또는",
    one_click_login: "원클릭 로그인",
    account_login: "계정 로그인",
    voucher_login: "바우처 로그인",
  },
  
};
